trigger: none

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5c348824-825f-4004-a841-5ccd8b0eb3cd'
  imageRepository: 'flaskwebapp'
  containerRegistry: 'devopsacr5c6ma.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'


# app-ci YAML pipeline
# We are setting up a pipeline resource that references the security-lib-ci
# pipeline and setting up a pipeline completion trigger so that our app-ci
# pipeline runs when a run of the security-lib-ci pipeline completes
resources:
  pipelines:
  - pipeline: update-yaml-pipeline # Name of the pipeline resource.
    source: Flask-Webapp-CI # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

steps:
- bash: echo "Update-yaml-manifests after Flask-Webapp-CI completes"
- bash: ls -l
- bash: "sed -i 's#docker0498/flask-new#$(containerRegistry)/$(imageRepository):$(tag)#g' deployment.yaml"





 



