trigger: none

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '135dc7df-87cd-475e-a125-95704ca72cb9'
  imageRepository: 'flaskwebapp'
  containerRegistry: 'devopsacr4t5lo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  major: 1
  minor: $[counter(variables['major'], 100)]



# app-ci YAML pipeline
# We are setting up a pipeline resource that references the security-lib-ci
# pipeline and setting up a pipeline completion trigger so that our app-ci
# pipeline runs when a run of the security-lib-ci pipeline completes
resources:
  pipelines:
  - pipeline: update-yaml-pipeline # Name of the pipeline resource.
    source: Flask-Webapp-CI # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

jobs:
- job: CommitJob
  displayName: 'Commit to GitHub'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true

  - bash: "sed -i 's#$(containerRegistry)/$(imageRepository):*$(date +%Y%m%d_%M)37#$(containerRegistry)/$(imageRepository):$(minor)#g' deployment.yaml"

  - task: CmdLine@2
    inputs:
      script: |

        git config --global user.email "prithviraj1998@hotmail.com"

        git config --global user.name "prithvirajkc"

        git init 

        git add . 
      
        git commit -m "updating tag $(minor)"

        git push origin HEAD:main





 



