apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python 
    spec:
      containers:
        - name: flask-webapp 
          image: docker0498/flask-new
          resources: {} 
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 3
            periodSeconds: 5
            

          
          
          