apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp1
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt  
spec:
  rules:
     - host: kubeprithvi.com
       http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-svc
                port: 
                  number: 5000
  tls:
  - hosts:
    - kubeprithvi.com
    secretName: app-secret 