apiVersion: v1
kind: Secret
metadata:
  name: azure-config-file
  namespace: default
type: Opaque
data:
  azure.json: ewogICAgInRlbmFudElkIjogIjQ3NTNlOTMyLTNiYTUtNGUxYy1iODY0LTBmYjQwMTI3NDhkZSIsCiAgICAic3Vic2NyaXB0aW9uSWQiOiAiYzY0NWY0ZGQtNzg2OS00ZWU2LTliM2QtYWMzODdlZWM5MmU0IiwKICAgICJyZXNvdXJjZUdyb3VwIjogImRldm9wcy1yZyIsCiAgICAiYWFkQ2xpZW50SWQiOiAiOTAwOTk0MzEtNDQwZS00N2E3LTk2YmEtMjVkN2MxZGE5NThmIiwKICAgICJhYWRDbGllbnRTZWNyZXQiOiAiMXZYOFF+Qy5vUzJIbEx2cU5nOTZHREZJd21xbjh5NGd2VFBacGF4aSIKICB9


